# Generated by Django 4.2.7 on 2024-01-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('uuid', models.CharField(max_length=5)),
                ('visitors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='account_app.visitormodel')),
            ],
        ),
    ]
